spring:
  datasource:
    url:                "jdbc:postgresql://localhost:2345/game"
    username:           "postgres"
    password:           "postgres"
    driver-class-name:  "org.postgresql.Driver"
